#!/usr/bin/env python3
"""Mark build script for cnn_stripped.ipynb — DO NOT edit this file directly; regenerate."""
import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.10"},
}

cells = []

# ───────────────────────────── Markdown 1: title/hypothesis ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""# 1D CNN (Stripped — No Positional Encoding) for Exoplanet Detection

## Hypothesis

The original `cnn.ipynb` used **21 features per observation** — 3 raw measurements + **16 sinusoidal BJD positional encoding channels** + 2 activity indices — and scored **ROC-AUC = 0.6490**, *worse* than the RF baseline (0.7994) and the Transformer (0.6793).

**The 16 positional encoding channels were drowning the signal.**

The sinusoidal encodings (8 log-spaced periods from 1 d rotation to 7300 d survey span) handed the conv kernels 16 channels of phase coordinates that — for a small ~2000-star dataset — the model couldn't reliably separate from noise. Each output channel of the first conv mixes *all 21 input channels*, so 16/21 ≈ 76% of every learned feature detector was driven by phase coordinates rather than by the physical measurements themselves.

This notebook strips it back to **4 raw measurement channels**: `[rv_centered, rv_err, RHKp, Halpha]`. The convolution still slides across observations in **chronological order** (preserved by sorting each star's observations by `bjd`), but the kernel now learns purely from **measurement values and their local co-occurrence patterns** — an RV excursion that lines up with an activity spike, a quasi-periodic wiggle across consecutive epochs — without the noise floor of 16 sinusoidal channels sitting under them.

### What changes vs. the original CNN

| Aspect | Original `cnn.ipynb` | This stripped variant |
|---|---|---|
| Features per observation | 21 (3 raw + 16 BJD-sinusoidal + 2 activity) | **4** (rv_centered, rv_err, RHKp, Halpha) |
| Positional encoding | 8 log-spaced periods × sin/cos = 16 channels | **None** — chronological order is implicit |
| Architecture | 21→128→128→48, 2×48=96 head input | **4→64→64→32**, 2×32=64 head input (~50-100K params) |
| Hypothesis | Sinusoidal PE helps the conv locate events in time | Sinusoidal PE was noise; raw measurements are enough |

### Architecture Overview

```
  Input: (B, T, 4)         ← [rv_centered, rv_err, RHKp, Halpha], zero-padded with mask
      │
      ▼  Conv1d(4 → 64, k=5, pad='same') + BatchNorm + GELU + Dropout(0.3)
      │
      ▼  Conv1d(64 → 64, k=5, pad='same') + BatchNorm + GELU + Dropout(0.3)
      │
      ▼  Conv1d(64 → 32, k=3, pad='same') + BatchNorm + GELU + Dropout(0.3)
      │
      ▼  Masked global avg + max pool (concat) → (B, 64)
      │
      ▼  Linear(64 → 32) + GELU + Dropout → Linear(32 → 1)   (logit)
```

Shrinking the conv widths (128/128/48 → 64/64/32) keeps the parameter count in the same ~50-100K band as the original despite the input shrinking 5× — the headline test is whether the **signal-to-noise of the input** improved, not whether the model got bigger.

### Design Decisions (carried over from the original)

| Choice | Rationale |
|---|---|
| **4 raw channels, no PE** | Hypothesis under test: sinusoidal PE was noise; raw measurements + chronological order should be enough. |
| **5-kernel convs** | Same receptive field as the original (≈11 after the k=3 layer) — captures short-lived RV/activity excursions without global dependence. |
| **'same' padding + BatchNorm** | Preserves time resolution so every real observation contributes to the pool; BatchNorm stabilises the long-tailed feature distributions. |
| **Concat global avg + max pool** | Mean summarises typical behaviour; max finds the most extreme local feature (the RV excursion). 2×32 = 64-dim head input. |
| **sqrt(n_neg/n_pos) pos_weight** | Milder than the raw ~4.3:1 ratio — strong enough to recover positives, gentle enough not to flood with false alarms. |
| **Cosine LR + 5-epoch warmup** | Warmup avoids early loss spikes; cosine gives smooth decay. |
| **weight_decay=5e-3 + clip=1.0** | Strong L2 on a small model; gradient clipping guards against activity-spike-induced huge gradients. |
| **patience=15** | Generous patience since per-epoch val loss is noisy at this dataset size."""))

# ───────────────────────────── Markdown 2: section 1 ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""## 1. Load Data & Build Per-Observation Feature Sequences

Each star becomes a variable-length sequence of **4-dim observation vectors**:

- `rv_centered` — the per-star mean-subtracted radial velocity (the host star's RV wiggle around zero)
- `rv_err`      — photon-limited measurement uncertainty on the RV
- `RHKp`        — Mount-Wilson S-index proxy for chromospheric magnetic activity
- `Halpha`      — Balmer-α line core index, second activity indicator

No `exposure_time`, no `bjd` raw value, **no sinusoidal positional encoding**. The conv kernel has no notion of absolute time and must learn purely from the **values** of the four measurements and how they line up with each other over consecutive epochs (chronological order is preserved by sorting each star's observations by `bjd`). The hypothesis is that the 16 phase-coordinate channels were the dominant noise source and removing them will let the kernel focus on the physical measurements."""))

# ───────────────────────────── Code cell 1 ─────────────────────────────
cells.append(nbf.v4.new_code_cell("""import pandas as pd
import numpy as np

observations = pd.DataFrame(pd.read_pickle('/kaggle/input/datasets/maanav0114/harps-n-dataset/observations.pkl'))

# ── Build per-star 4-feature sequences, sorted by bjd (chronological order) ──
# Schema: star_name, bjd, rv, rv_err, exposure_time, RHKp, Halpha, has_exoplanets, rv_centered
def build_sequences(star_names):
    sequences = []
    for star in star_names:
        star_obs = observations[observations['star_name'] == star].sort_values('bjd')
        rows = []
        for idx in range(len(star_obs)):
            row = star_obs.iloc[idx]
            # 4 raw measurements — NO positional encoding, NO exposure_time
            features = [
                float(row['rv_centered']),
                float(row['rv_err']),
                float(row['RHKp']),
                float(row['Halpha']),
            ]
            rows.append(features)
        if rows:
            sequences.append(np.array(rows, dtype=np.float32))
    return sequences

pos_stars = list(set(observations[observations['has_exoplanets'] == 1]['star_name']))
neg_stars = list(set(observations[observations['has_exoplanets'] == 0]['star_name']))

pos_sequences = build_sequences(pos_stars)
neg_sequences = build_sequences(neg_stars)

print(f"Positive stars: {len(pos_sequences)}, total observations: {sum(len(x) for x in pos_sequences)}")
print(f"Negative stars: {len(neg_sequences)}, total observations: {sum(len(x) for x in neg_sequences)}")
print(f"Feature dimension per observation: {pos_sequences[0].shape[1]}  (expected 4)")"""))

# ───────────────────────────── Markdown 3: section 2 ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""## 2. Train / Validation / Test Split + Standardization

- **Split by star** (never by observation) — prevents leakage of an individual star's epochs across splits.
- **60/20/20** via two `train_test_split` calls: `stratify=y` on the first, `stratify=y_temp` on the second (operating on the temp arrays — using `stratify=y` here would be a dimension-mismatch bug).
- **Standardize using training stats only** — fit `mean`/`std` on the *training* observations, then apply to val and test. Prevents any information leakage from val/test.
- **Truncate sequences to `max_seq_len=100`** observations (longer sequences are rare and truncation bounds memory)."""))

# ───────────────────────────── Code cell 2 ─────────────────────────────
cells.append(nbf.v4.new_code_cell("""import torch
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split
import random

def seed_everything(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True

seed = 42
seed_everything(seed)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

MAX_SEQ_LEN = 100

# ── Step 1: split sequences and labels via stratify ──
all_seq = pos_sequences + neg_sequences
all_lab = [1] * len(pos_sequences) + [0] * len(neg_sequences)

X_train, X_temp, y_train, y_temp = train_test_split(
    all_seq, all_lab, test_size=0.4, random_state=seed, stratify=all_lab
)
# Second split uses stratify=y_temp (NOT stratify=y — that would mismatch dimensions)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=seed, stratify=y_temp
)

# ── Step 2: standardize using TRAINING stats only ──
train_all = np.concatenate(X_train, axis=0)  # (n_train_obs, 4)
feat_mean = train_all.mean(axis=0)
feat_std  = np.clip(train_all.std(axis=0), 1e-8, None)

def standardize(seq_list):
    return [(s - feat_mean) / feat_std for s in seq_list]

X_train = standardize(X_train)
X_val   = standardize(X_val)
X_test  = standardize(X_test)

# ── Step 3: truncate sequences longer than MAX_SEQ_LEN (truncate from the end) ──
truncate_count = 0
for seq_list in [X_train, X_val, X_test]:
    for i in range(len(seq_list)):
        if len(seq_list[i]) > MAX_SEQ_LEN:
            seq_list[i] = seq_list[i][:MAX_SEQ_LEN]
            truncate_count += 1

all_lens = [len(x) for x in X_train + X_val + X_test]
print(f"Truncated {truncate_count} stars")
print(f"Splits: train={len(X_train)} ({sum(y_train)} pos), "
      f"val={len(X_val)} ({sum(y_val)} pos), "
      f"test={len(X_test)} ({sum(y_test)} pos)")
print(f"Sequence lengths: min={min(all_lens)}, max={max(all_lens)}, "
      f"median={int(np.median(all_lens))}")"""))

# ───────────────────────────── Markdown 4: section 3 ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""## 3. Dataset & Collate Function (Padding + Mask)

Each star has a variable number of observations, so each batch is padded to the **longest sequence in that batch**. A boolean mask records which positions are real observations vs. padding — used during training (so we don't backprop on padding) and at pooling time (so padding doesn't dilute the global summary nor fire the max pool on zeros).

The collate function returns `(padded_sequences, mask, labels)` where:
- `padded_sequences`: `(B, T_max_batch, 4)` float32 — features, zero-filled past real obs
- `mask`: `(B, T_max_batch)` boolean — **True** where real data, **False** where padding
- `labels`: `(B,)` float32 — 0/1"""))

# ───────────────────────────── Code cell 3 ─────────────────────────────
cells.append(nbf.v4.new_code_cell("""class StarDataset(Dataset):
    def __init__(self, sequences, labels):
        self.data = sequences
        self.labels = labels

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        star = torch.tensor(self.data[idx], dtype=torch.float32)
        label = torch.tensor(self.labels[idx], dtype=torch.float32)
        return star, label

def collate_stars(batch):
    \"\"\"Pad variable-length star sequences to the longest in the batch.

    Returns:
        padded:  (B, max_seq_len, 4)    — features, zero-padded past real obs
        mask:    (B, max_seq_len) bool  — True where real data, False where padding
        labels:  (B,)                    — 0/1 labels
    \"\"\"
    stars, labels = zip(*batch)
    max_len = max(s.shape[0] for s in stars)

    padded, mask = [], []
    for star in stars:
        seq_len, feat_dim = star.shape
        pad_len = max_len - seq_len
        if pad_len > 0:
            padding = torch.zeros(pad_len, feat_dim)
            padded_star = torch.cat([star, padding], dim=0)
        else:
            padded_star = star
        star_mask = torch.cat([torch.ones(seq_len), torch.zeros(pad_len)]).bool()
        padded.append(padded_star)
        mask.append(star_mask)

    return torch.stack(padded), torch.stack(mask), torch.stack(labels)

train_dataset = StarDataset(X_train, y_train)
val_dataset   = StarDataset(X_val,   y_val)
test_dataset  = StarDataset(X_test,  y_test)

batch_size = 32
pin = device.type == 'cuda'
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,  drop_last=False, collate_fn=collate_stars, pin_memory=pin)
val_loader   = DataLoader(val_dataset,   batch_size=batch_size, shuffle=False, drop_last=False, collate_fn=collate_stars, pin_memory=pin)
test_loader  = DataLoader(test_dataset,  batch_size=batch_size, shuffle=False, drop_last=False, collate_fn=collate_stars, pin_memory=pin)

print(f"Train: {len(train_dataset)} stars / {len(train_loader)} batches")
print(f"Val:   {len(val_dataset)} stars / {len(val_loader)} batches")
print(f"Test:  {len(test_dataset)} stars / {len(test_loader)} batches")"""))

# ───────────────────────────── Markdown 5: section 4 ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""## 4. The Stripped 1D CNN Model

A small stack of **three 1D convolutions** (4→64, 64→64, 64→32) with kernel sizes 5, 5, 3 ('same' padding to preserve time resolution), each followed by **BatchNorm → GELU → Dropout(0.3)**. A masked global pool (concat of average and max pooling, both masked to ignore padded positions) feeds a compact head: `Linear(64→32) → GELU → Dropout → Linear(32→1)`.

**Why this shape:**
- Channels `4 → 64 → 64 → 32`: enough capacity to learn rich feature detectors over the 4 raw measurements, but small enough (≈50-100K params) to resist overfitting a ~2000-star dataset.
- Kernel size 5+5+3 gives a receptive field of ≈11 observations — captures short-duration RV/activity-correlated excursions without making every output depend on the entire sequence.
- **Concat avg + max pool** combines mean-of-feature-typicalization with peak-finding — `2×32 = 64` features feed the head.
- Padding positions are masked at the global average; the max pool sets padding to `-inf` so it never fires on padded zeros."""))

# ───────────────────────────── Code cell 4 ─────────────────────────────
cells.append(nbf.v4.new_code_cell("""import torch.nn as nn
import torch.nn.functional as F

class MaskedConv1dBlock(nn.Module):
    \"\"\"Conv1d('same') + BatchNorm + GELU + Dropout.

    Input/output: (B, C_in, T) → (B, C_out, T) — time resolution preserved.
    \"\"\"
    def __init__(self, in_ch, out_ch, kernel_size, dropout=0.3):
        super().__init__()
        pad = kernel_size // 2  # 'same' padding (assumes odd kernel)
        self.conv = nn.Conv1d(in_ch, out_ch, kernel_size=kernel_size, padding=pad)
        self.bn   = nn.BatchNorm1d(out_ch)
        self.act  = nn.GELU()
        self.drop = nn.Dropout(dropout)

    def forward(self, x):
        return self.drop(self.act(self.bn(self.conv(x))))

class MaskedAvgMaxPool(nn.Module):
    \"\"\"Concatenates masked global mean and masked global max pooling.

    Input: (B, C, T), mask (B, T) with True = real obs.
    Output: (B, 2C).
    \"\"\"
    def forward(self, x, mask):
        m = mask.unsqueeze(1).type_as(x)  # (B, 1, T)
        denom = m.sum(dim=2).clamp_min(1.0)
        avg = (x * m).sum(dim=2) / denom                       # (B, C)
        masked_x = x.masked_fill(m == 0, float('-inf'))        # padding → -inf for max
        mx = masked_x.max(dim=2).values                         # (B, C)
        mx = torch.nan_to_num(mx, nan=0.0, posinf=0.0, neginf=0.0)
        return torch.cat([avg, mx], dim=1)                       # (B, 2C)

class ExoplanetCNN(nn.Module):
    \"\"\"3-layer 1D CNN on 4 raw per-observation measurements (no positional encoding).

    Operates on sequences of shape (B, T, in_dim). Convention here is
    (batch, time, features) — transposed to (batch, channels=time) for Conv1d internally.
    \"\"\"
    def __init__(self, in_dim=4, hidden=64, tail=32, head_hidden=32, dropout=0.3):
        super().__init__()
        self.conv1 = MaskedConv1dBlock(in_dim,  hidden, 5, dropout)
        self.conv2 = MaskedConv1dBlock(hidden, hidden, 5, dropout)
        self.conv3 = MaskedConv1dBlock(hidden, tail,    3, dropout)
        self.pool  = MaskedAvgMaxPool()  # concat → (B, 2*tail=64)
        self.head = nn.Sequential(
            nn.Linear(2 * tail, head_hidden),  # 64 → 32
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(head_hidden, 1),
        )

    def forward(self, x, mask):
        # x: (B, T, in_dim) → (B, in_dim, T) for Conv1d
        x = x.transpose(1, 2)
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.pool(x, mask)        # mask stays (B, T)
        return self.head(x).squeeze(-1)  # logits (B,)

model = ExoplanetCNN(in_dim=4).to(device)
print(model)
print(f"\\nTotal parameters: {sum(p.numel() for p in model.parameters()):,}")
print(f"Target: 50K-100K  -> {'OK' if 50000 <= sum(p.numel() for p in model.parameters()) <= 100000 else 'CHECK'}")"""))

# ───────────────────────────── Markdown 6: section 5 ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""## 5. Training Loop

- **Loss**: `BCEWithLogitsLoss` with `pos_weight = sqrt(n_neg / n_pos)` — milder than the raw ~4.3:1 ratio (square root gives ≈2.07). Recovery of positives without flooding with false alarms.
- **Optimizer**: Adam, `lr = 1e-3`, `weight_decay = 5e-3`.
- **LR schedule**: cosine annealing with a **5-epoch linear warmup**.
- **Gradient clipping**: `max_norm = 1.0`.
- **Early stopping**: `patience = 15` epochs on validation loss; best checkpoint restored at the end."""))

# ───────────────────────────── Code cell 5 ─────────────────────────────
cells.append(nbf.v4.new_code_cell("""from torch.optim import Adam
from torch.optim.lr_scheduler import LambdaLR
import math

n_pos = int(sum(y_train))
n_neg = int(len(y_train) - n_pos)
pos_weight = torch.tensor([math.sqrt(n_neg / n_pos)]).to(device)
print(f"pos_weight = {pos_weight.item():.4f}  (n_neg={n_neg}, n_pos={n_pos}, raw ratio={n_neg/n_pos:.2f})")

criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = Adam(model.parameters(), lr=1e-3, weight_decay=5e-3)

warmup_epochs = 5
max_epochs = 100

def lr_lambda(epoch):
    if epoch < warmup_epochs:
        return (epoch + 1) / warmup_epochs                       # linear warmup
    progress = (epoch - warmup_epochs) / max(1, max_epochs - warmup_epochs)
    return 0.5 * (1 + math.cos(math.pi * progress))             # cosine decay

scheduler = LambdaLR(optimizer, lr_lambda)

train_losses, val_losses = [], []
train_accs, val_accs = [], []

best_val_loss = float('inf')
best_model_state = None
patience = 15
epochs_no_improve = 0

for epoch in range(max_epochs):
    # ── Train ──
    model.train()
    train_loss, train_correct, train_total = 0, 0, 0
    for padded, mask, labels in train_loader:
        padded = padded.to(device)
        mask    = mask.to(device)
        labels  = labels.to(device)

        optimizer.zero_grad()
        logits = model(padded, mask)
        loss = criterion(logits, labels)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        train_loss   += loss.item() * padded.size(0)
        preds         = (logits > 0).float()
        train_correct += (preds == labels).sum().item()
        train_total   += padded.size(0)

    scheduler.step()

    # ── Validate ──
    model.eval()
    val_loss, val_correct, val_total = 0, 0, 0
    with torch.no_grad():
        for padded, mask, labels in val_loader:
            padded = padded.to(device)
            mask    = mask.to(device)
            labels  = labels.to(device)
            logits = model(padded, mask)
            loss = criterion(logits, labels)
            val_loss   += loss.item() * padded.size(0)
            preds       = (logits > 0).float()
            val_correct += (preds == labels).sum().item()
            val_total   += padded.size(0)

    epoch_train_loss = train_loss / train_total
    epoch_val_loss   = val_loss   / val_total
    train_acc         = train_correct / train_total
    val_acc           = val_correct   / val_total
    train_losses.append(epoch_train_loss); val_losses.append(epoch_val_loss)
    train_accs.append(train_acc); val_accs.append(val_acc)

    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        best_model_state = {k: v.clone() for k, v in model.state_dict().items()}
        epochs_no_improve = 0
        marker = " *"
    else:
        epochs_no_improve += 1
        marker = ""

    print(f"Epoch {epoch+1:3d}/{max_epochs} "
          f"| Train Loss: {epoch_train_loss:.4f} Acc: {train_acc:.4f} "
          f"| Val Loss: {epoch_val_loss:.4f} Acc: {val_acc:.4f} "
          f"| LR: {scheduler.get_last_lr()[0]:.6f}{marker}")

    if epochs_no_improve >= patience:
        print(f"\\nEarly stopping at epoch {epoch+1} — no improvement for {patience} epochs.")
        break

if best_model_state is not None:
    model.load_state_dict(best_model_state)
    print(f"Restored best model (val loss = {best_val_loss:.4f})")

torch.save(model.state_dict(), "/kaggle/working/cnn_stripped.pth")
print("Saved model to /kaggle/working/cnn_stripped.pth")"""))

# ───────────────────────────── Markdown 7: section 6 ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""## 6. Training Curves

Symptom of the hypothesis: if positional encoding was noise, the stripped model should reach lower val loss and/or higher val accuracy than the original CNN with PE — and we'd expect train loss to behave more like val loss (less of the gap that PE-induced overfitting would create)."""))

# ───────────────────────────── Code cell 6 ─────────────────────────────
cells.append(nbf.v4.new_code_cell("""import matplotlib.pyplot as plt

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

ax1.plot(train_losses, label='Train Loss', color='#1f77b4')
ax1.plot(val_losses,   label='Val Loss',   color='#ff7f0e')
ax1.set_xlabel('Epoch'); ax1.set_ylabel('Loss'); ax1.set_yscale('log')
ax1.set_title('Loss vs. Epoch'); ax1.legend(); ax1.grid(True, alpha=0.3)

ax2.plot(train_accs, label='Train Acc', color='#1f77b4')
ax2.plot(val_accs,   label='Val Acc',   color='#ff7f0e')
ax2.set_xlabel('Epoch'); ax2.set_ylabel('Accuracy')
ax2.set_title('Accuracy vs. Epoch'); ax2.legend(); ax2.grid(True, alpha=0.3)

plt.tight_layout(); plt.show()"""))

# ───────────────────────────── Markdown 8: section 7 ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""## 7. Evaluation on the Test Set

Collect per-star probabilities on the held-out test split, then compute:
- **ROC-AUC** — threshold-independent; the principal comparison metric.
- **PR-AUC** (`average_precision_score`) — important under class imbalance (ROC-AUC can look optimistic when negatives vastly outnumber positives).
- **Best F1** — sweep the precision-recall curve and pick the threshold maximizing F1. The F1 denominator is `precision + recall + 1e-8` (the standard harmonic-mean form). An earlier notebook used `(precision*recall + recall + 1e-8)` — a bug that gave nonsensical F1 values; the correct formula is:
  ```
  F1 = 2 * precision * recall / (precision + recall + 1e-8)
  ```
- **Confusion matrix** at the best-F1 threshold."""))

# ───────────────────────────── Code cell 7 ─────────────────────────────
cells.append(nbf.v4.new_code_cell("""from sklearn.metrics import (roc_auc_score, average_precision_score,
                             precision_recall_curve, confusion_matrix,
                             classification_report)

model.eval()
all_probs, all_labels = [], []

with torch.no_grad():
    for padded, mask, labels in test_loader:
        padded = padded.to(device)
        mask    = mask.to(device)
        logits  = model(padded, mask)
        probs   = torch.sigmoid(logits)
        all_probs.extend(probs.cpu().numpy())
        all_labels.extend(labels.numpy())

all_probs  = np.array(all_probs)
all_labels = np.array(all_labels)

roc_auc = roc_auc_score(all_labels, all_probs)
pr_auc  = average_precision_score(all_labels, all_probs)

# ── Best F1 by sweeping the precision-recall curve ──
# F1 = 2 * P * R / (P + R + 1e-8)  — denominator is (P + R), NOT (P*R + R)
precisions, recalls, thresholds = precision_recall_curve(all_labels, all_probs)
f1_scores = 2 * precisions * recalls / (precisions + recalls + 1e-8)
best_idx    = int(np.argmax(f1_scores))
best_thresh = float(thresholds[best_idx]) if best_idx < len(thresholds) else 0.5
best_f1        = float(f1_scores[best_idx])
best_precision = float(precisions[best_idx])
best_recall    = float(recalls[best_idx])

print(f"ROC-AUC      : {roc_auc:.4f}")
print(f"PR-AUC       : {pr_auc:.4f}")
print(f"Best F1      : {best_f1:.4f}  (threshold = {best_thresh:.4f})")
print(f"  @ best F1 : precision = {best_precision:.4f}, recall = {best_recall:.4f}")"""))

# ───────────────────────────── Markdown 9: confusion matrix ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""### Confusion Matrix at Best-F1 Threshold"""))

# ───────────────────────────── Code cell 8 ─────────────────────────────
cells.append(nbf.v4.new_code_cell("""preds = (all_probs >= best_thresh).astype(int)
cm = confusion_matrix(all_labels, preds)

plt.figure(figsize=(6, 6))
plt.imshow(cm, cmap='Blues', interpolation='nearest')
plt.colorbar(shrink=0.6)

classes = ['No Planet', 'Planet']
plt.xticks([0, 1], classes, fontsize=12)
plt.yticks([0, 1], classes, fontsize=12)
plt.xlabel('Predicted Label', fontsize=14)
plt.ylabel('True Label',      fontsize=14)
plt.title(f'Confusion Matrix (threshold={best_thresh:.4f})', fontsize=14)

for i in range(2):
    for j in range(2):
        plt.text(j, i, f'{cm[i, j]}', ha='center', va='center', fontsize=16, color='red')

plt.tight_layout(); plt.show()

tn, fp, fn, tp = cm.ravel()
print(f"TP={tp}  FP={fp}  FN={fn}  TN={tn}")
print(f"Accuracy : {(tp + tn) / (tp + tn + fp + fn):.4f}")
print(f"Precision: {tp / (tp + fp):.4f}    Recall: {tp / (tp + fn):.4f}")"""))

# ───────────────────────────── Markdown 10: classification report ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""### Classification Report at Default and Optimal Thresholds"""))

# ───────────────────────────── Code cell 9 ─────────────────────────────
cells.append(nbf.v4.new_code_cell("""print("=" * 60)
print(f"REPORT AT DEFAULT THRESHOLD (0.5)")
print("=" * 60)
preds_05 = (all_probs >= 0.5).astype(int)
print(classification_report(all_labels, preds_05, target_names=['No Planet', 'Planet']))

print("=" * 60)
print(f"REPORT AT OPTIMAL THRESHOLD ({best_thresh:.4f})")
print("=" * 60)
preds_opt = (all_probs >= best_thresh).astype(int)
print(classification_report(all_labels, preds_opt, target_names=['No Planet', 'Planet']))"""))

# ───────────────────────────── Markdown 11: section 8 comparison ─────────────────────────────
cells.append(nbf.v4.new_markdown_cell("""## 8. Comparison with Other Models

| Model | Input | Features/obs | ROC-AUC | PR-AUC | Best F1 |
|---|---|---|---|---|---|
| Random Forest (16 physical summary stats) | per-star aggregates | — | **0.7994** | **0.4658** | **0.5221** |
| Transformer (raw sequences, attention) | (T, 21) raw obs | 21 | 0.6793 | — | — |
| 1D CNN **with** positional encoding (original `cnn.ipynb`) | (T, 21) raw obs | 21 | 0.6490 | 0.3049 | 0.3887 |
| **1D CNN stripped — no PE (this notebook)** | (T, 4) raw obs | 4 | *below* | *below* | *below* |

### If the hypothesis holds:

The stripped CNN should land above the **0.6490** ROC-AUC / **0.3049** PR-AUC / **0.3887** Best F1 of the original CNN-with-PE. The decisive comparison is against the original CNN, since this variant differs from the original **only** in dropping the 16 positional-encoding channels (and the correspondingly narrower conv widths) — same architecture骨架, same training recipe, same splits.

- If stripped CNN beats 0.6490 ROC-AUC → the hypothesis (PE was noise) is supported.
- If stripped CNN also closes in on the RF baseline (0.7994) → temporal structure in the raw measurements was the right signal all along and PE was actively hiding it.
- If stripped CNN comes in below the original CNN → the PE was carrying information after all and the noise hypothesis was wrong."""))

# ───────────────────────────── Code cell 10 ─────────────────────────────
cells.append(nbf.v4.new_code_cell("""import pandas as pd

comparison = pd.DataFrame([
    {"Model": "RF (16 physical features)",
     "Input": "per-star aggregates",
     "ROC-AUC": 0.7994, "PR-AUC": 0.4658, "Best F1": 0.5221},
    {"Model": "Transformer (raw sequences)",
     "Input": "(T, 21) raw obs",
     "ROC-AUC": 0.6793, "PR-AUC": float('nan'), "Best F1": float('nan')},
    {"Model": "1D CNN with PE (original)",
     "Input": "(T, 21) raw obs",
     "ROC-AUC": 0.6490, "PR-AUC": 0.3049, "Best F1": 0.3887},
    {"Model": "1D CNN stripped no-PE (this notebook)",
     "Input": "(T, 4) raw obs",
     "ROC-AUC": roc_auc, "PR-AUC": pr_auc, "Best F1": best_f1},
])

print(comparison.to_string(index=False, float_format=lambda x: f"{x:.4f}"))

print()
print("Verdict relative to the original CNN (with PE — the controlling baseline):")
if roc_auc > 0.6490 and pr_auc > 0.3049 and best_f1 > 0.3887:
    print(f"  ✓ HYPOTHESIS SUPPORTED: stripped CNN ({roc_auc:.4f} ROC-AUC, {pr_auc:.4f} PR-AUC, {best_f1:.4f} F1) BEATS the original CNN-with-PE on all three metrics — positional encoding was noise.")
elif roc_auc > 0.6490:
    print(f"  • Mixed: stripped CNN ({roc_auc:.4f}) beats original CNN on ROC-AUC but not on all three metrics.")
elif roc_auc < 0.6490:
    print(f"  ✗ HYPOTHESIS REJECTED: stripped CNN ({roc_auc:.4f}) underperforms the original CNN-with-PE (0.6490). PE was carrying information.")

print()
print("Verdict relative to baselines:")
if roc_auc > 0.7994:
    print(f"  ✓ Stripped CNN ({roc_auc:.4f}) BEATS the RF baseline (0.7994). Temporal structure in raw measurements carries signal summary statistics miss.")
elif roc_auc > 0.6793:
    print(f"  • Stripped CNN ({roc_auc:.4f}) beats the Transformer (0.6793) but trails the RF baseline (0.7994).")
else:
    print(f"  ✗ Stripped CNN ({roc_auc:.4f}) trails both the RF baseline (0.7994) and the Transformer (0.6793).")"""))

nb.cells = cells
nbf.write(nb, "/home/maanav0114/Documents/mled/cnn_stripped.ipynb")
print("Wrote /home/maanav0114/Documents/mled/cnn_stripped.ipynb")
print(f"Cells: {len(cells)}  ({sum(1 for c in cells if c['cell_type']=='markdown')} markdown, {sum(1 for c in cells if c['cell_type']=='code')} code)")
